name: first_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: macos-latest
    steps:
     - name: first-step
       run: echo "Hello world"
     - name: second-step 
       run: echo "Goodnight"
